services:
  db:
    image: docker.io/postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=jsus
      - POSTGRES_DB=tasks

  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tasks
      - DB_USER=jsus
      - DB_PASSWORD=example
    depends_on:
      - db